  # https://medium.com/@suruti94/debugging-k8s-podsecuritypolicy-related-issues-9730c90d9eff
  # https://github.com/kubernetes/kubernetes/issues/65716
  # RTFM: RBAC, Security, Podsecurity, whatnot. E.g.: https://kubernetes.io/docs/reference/access-authn-authz/rbac/, https://kubernetes.io/docs/concepts/security/rbac-good-practices/, https://kubernetes.io/docs/concepts/security/pod-security-policy/
  # https://github.com/rancher/rancher/issues/23077
  # TODO: reduce privileges!
  # https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/policy/pod-security-policy/
  # https://kubernetes.io/docs/concepts/security/pod-security-standards/
# "kubernetes deprecated podsecuritypolicies in favor of admission configurations. However, these are not available inside the cluster."
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: nextflow-psp
spec:
  privileged: true
  allowPrivilegeEscalation: false
  allowedCapabilities: 
  - '*'
  hostIPC: false
  hostNetwork: false
  hostPID: false
  #allowedHostPaths:
  #- pathPrefix: "/dev/null"
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes: #["persistentVolumeClaim", "nfs", "projected"]
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: nextflow-role
rules:
 - apiGroups: [""]
   resources: ["pods","pods/status", "pods/log", "pods/exec"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
 - apiGroups: ["batch"]
   resources: ["jobs", "jobs/status"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
 - apiGroups: ["extensions"] # role needs to be allowed access to podsecuritypolicy!
   resources: ["podsecuritypolicies"]
   resourceNames: ["nextflow-psp"]
   verbs: ["use"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: nextflow-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: nextflow-rolebinding
subjects:
  - kind: ServiceAccount
    name: nextflow-serviceaccount
    namespace: default
roleRef:
  kind: Role
  name: nextflow-role
  apiGroup: rbac.authorization.k8s.io
