# This still does not work! For the first access of multiple files, this seems to work but quickly breaks
# https://github.com/kubernetes/cloud-provider-openstack/issues/1248
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: magnum-csi
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubernetes.io/is-default-class: "false"
  name: csi-cinder-multiattach
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: "__DEFAULT__"
  multiattach: "true"
---
# If using a provisioner, you usually don't create the PV on your own. Just create a PVC requiring that created storage class and GKE will provide the PV with the requested storage size and kind for you:
# See: https://stackoverflow.com/a/55964096
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
  name: mypvc
spec:
  storageClassName: 'csi-cinder-multiattach'
  resources:
    requests:
      storage: 50G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
