apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    purpose: execution
spec:
  serviceAccountName: nextflow-serviceaccount
  securityContext:
    runAsUser: 0
  containers:
  - name: execution
    image: floriankaterndahl/nf-submitter:0.0.5
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    volumeMounts:
      - mountPath: /input
        name: input
    resources:
      limits:
        memory: 28G
        cpu: "3"
        ephemeral-storage: 32G
  restartPolicy: Never
  volumes:
    - name: input
      persistentVolumeClaim:
        claimName: mypvc
    