apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    purpose: execution
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: execution
    image: floriankaterndahl/sits-gpu:latest
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    resources:
      limits:
        nvidia.com/gpu: 1
  tolerations:
      - key: "node.cloudferro.com/type"
        operator: "Equal"
        value: "gpu"
  restartPolicy: Never
